---
# - name: download zookeeper binary file
#   get_url:
#     url: https://www-us.apache.org/dist/zookeeper/zookeeper-3.4.14/zookeeper-3.4.14.tar.gz
#     dest: "{{ repo }}"

- name: "Create repo directory"
  file:
    path: "{{ repo }}"
    state: directory

# - name: "Copy zookeeper tar file on hostvars['hosts']"
#   copy:
#     src: "{{ repo }}/{{ app_name }}-{{ app_version }}.tar.gz"
#     dest: "{{ role_bigdata_dir }}"
#   delegate_to: localhost

# - name: download zookeeper binary file
#   local_action:
#     get_url:
#       url: https://www-us.apache.org/dist/zookeeper/zookeeper-3.4.14/zookeeper-3.4.14.tar.gz
#       dest: "{{ repo }}"
