---
- name: deploy kafla cluster
  hosts: kafka
  gather_facts: no
  become: true
  vars:
    - kafka:
      - {
        name: kafka,
        user: "{{ name }}",
        group: "kafka",
        gid: "5001",
        uid: "5001",
        url: http://apache.crihan.fr/dist/kafka/2.3.0/kafka_2.11-2.3.0.tgz,
        binary: "kafka_2.11-2.3.0",
        binary_extension: ".tgz"
        }
  roles:
    - { role: role_system, state: install }
    - { role: role_user, state: create }
    - { role: role_applicatif, state: install }
    - { role: role_manage_ssh, app_user: jcadmin }
