---
- name: "deploy {{ app_name }} daemon"
  template:
    src: " {{ app_name }}_daemon.sh.j2"
    dest: "{{ system_initd }}/{{ app_name }}"
    mode: "0755"

- name: "enable service {{ app_name }} "
  systemd:
    name: " {{ app_name }} "
    enabled: yes
