---
- name: configure postfix directory
  template:
    src: "{{ item }}.j2"
    dest: "{{ role_postfix_conf }}/{{ role_postfix_dir[0] }}/{{ item }}"
    path: "{{ role_postfix_conf }}/{{ item }}"
    state: directory
  with_items: "{{ role_conf_file }}"
