---
- name: Check that all variables are defined
  assert:
    that:
      - "{{ project_user }} is defined"
      - "{{ postfix_name }} is defined"
      - "{{ postfix_port }} is defined"
      - "{{ postfix_group }} is defined"

- name: Create postfix directories
  import_tasks: create_directory.yaml
  when: state in ['create']

- name: Create postfix instance
  import_tasks: create_instance.yaml
  when: state in ['create']

# - name: Configure postfix instance
#   import_tasks: configure_instance.yaml
#   when: state in ['create']
