---
- name: Check taht all variables are defined
  assert:
    that:
      - "{{ item.user }} is defined"
      - "{{ item.name }} is defined"
      - "{{ item.port }} is defined"
      - "{{ item.group }} is defined"
  with_items: "{{ role_postfix_instance_list }}"

- name: Create postfix directories
  import_tasks: create_directory.yaml
  when: state in ['create']

- name: Create postfix instance
  import_tasks: create_instance.yaml
  when: state in ['create']

- name: Configure postfix instance
  import_tasks: configure_instance.yaml
  when: state in ['create']
