---
- name: "create group {{ item.group }}"
  group:
    name: "{{ item.group }}"
    gid: "{{ item.gid }}"
    state: present

- name: "create user {{ item.user }}"
  user:
    name: "{{ item.user }}"
    groups: "{{ item.group }},{{ sys_group }}"
    append: yes
    uid: "{{ item.uid }}"
