---
- name: "Install {{ app_name }}"
  import_tasks: install_kafka.yaml
  when: state in ['install']

- name: "enable service {{ app_name }}"
  import_tasks: enable_service.yaml
  when: state in ['install']

- name: "configure {{ app_name }}"
  import_tasks: configure_kafka.yaml
  when: state in ['install']

- name: "create daemon {{ app_name }}"
  import_tasks: configure_kafka.yaml
  when: state in ['install']
