---
- import_tasks: install.yaml
  when: state in ['install']

- import_tasks: enable_service.yaml
  when: state in ['install']

- import_tasks: disable_service.yaml
  when: state in ['install']
