---
- name: create directory
  file:
    path: "{{ item }}"
    state: directory
    group: "{{ sys_group }}"
    mode: "0774"
    recurse: yes
    owner: "{{ app_user }}"
  loop:
    - "{{ app_data }}"
    - "{{ app_var }}"
