---
- name: check if binary file is already download
  stat:
    path: "{{ sys_repo }}/{{ app_binary }}{{ app_binary_extension }}"
  register: R_check_binary
  delegate_to: localhost

- name: download binary file
  get_url:
    url: "{{ app_url }}"
    dest: "{{ sys_repo }}"
    owner: "{{ sys_user }}"
    group: "{{ app_group }}"
  delegate_to: localhost
  when: R_check_binary.stat.exists

- name: unarchive the binary tar file on target
  unarchive:
    src: "{{ sys_repo }}/{{ app_binary }}{{ app_binary_extension }}"
    dest: "{{ sys_app }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    copy: yes
    # creates: "{{ sys_app }}/{{ app_binary }}"

- name: "create link for {{ app_name }}"
  file:
    src: "{{ sys_app }}/{{ app_binary }}"
    dest: "{{ app_home }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    state: link

# - name: install packages
#   yum:
#     name: " {{ app_package }}"
#     update_cache: yes
