---
- name: check if binary file is already download
  shell: "ls {{ role_system.repo}} | grep {{ binary_name | quote }}"
  register: R_check_binary
  delegate_to: localhost

- name: download binary file
  get_url:
    url: " {{ item.url }}"
    dest: "{{ role_system.repo }}"
    owner: "{{ role_system.user }}"
    group: "{{ role_system.group }}"
  delegate_to: localhost
  when: R_check_binary.rc != 0

- name: unarchive the binary tar file on target
  unarchive:
    src: "{{ role_system.repo }}/{{ item.binary_name }}{{ item.binary_ext_file }}"
    dest: "{{ role_system.bin }}"
    owner: "{{ item.user }}"
    group: "{{ role_system.group }}"
    copy: yes
    creates: "{{ role_system.bin }}/{{ binary_name }}"

- name: "create link for {{ item.name }}"
  file:
    src: "{{ role_system.apps }}/{{item.binary_name}}"
    dest: "{{ item.home }}"
    owner: "{{ item.user }}"
    group: "{{ role_system.group }}"
    state: link

# - name: install packages
#   yum:
#     name: " {{ packages }}"
#     update_cache: yes
#   vars:
#     - "{{ packages }}"
