---
- name: check variable definition
  assert:
    that: "{{ item }} is defined"
  loop:
    - group_list
    - user_list

- name: check that user exist
  shell: "grep {{ item.user }} /etc/passwd"
  loop: "{{ user_list }}"
  register: R_CheckUser
  changed_when: R_CheckUser.rc != 0
  failed_when: False

- name: check that group exist
  shell: "grep {{ item.name }} /etc/passwd"
  loop: "{{ group_list }}"
  register: R_CheckGroup
  changed_when: R_CheckGroup.rc != 0
  failed_when: False

- name: "create group "
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    system: true
    local: true
  loop: "{{ group_list }}"
  when: R_CheckGroup.changed

- name: "create user"
  user:
    name: "{{ item.user }}"
    uid: "{{ item.uid }}"
    group: "{{ item.group }}"
    groups: "{{ item.groups }}"
    generate_ssh_key: "{{ item.ssh_key }}"
    home: "{{ role_manage_user_home }}"
    shell: "{{ role_manage_user_shell }}"
    system: true
    ssh_key_bits: 2048
    ssh_key_file: "{{ role_manage_user_ssh_key_file }}"
  loop: "{{ user_list }}"
  when: R_CheckUser.changed
