---
- name: slurp the pubkey for passing to other servers as authorized_key
  slurp:
    src: "{{role_manage_user_home}}/{{role_manage_user_ssh_key_file}}.pub"
  register: ssh_pubkey

- name: "add authorized key to user {{ item.user }}"
  authorized_key:
    user: "{{ item.user }}"
    state: present
    key: "{{ ssh_pubkey }}"
