---
- name: Set authorized key taken from file
  authorized_key:
    user: "{{ app_user }}"
    state: present
    key: "{{ lookup('file', '{{role_manage_user_home}}/{{role_manage_user_ssh_key_file}}.pub') }}"
