---
- name: Set authorized key taken from file
  authorized_key:
    user: "{{ item.user }}"
    state: present
    key: "{{lookup('file', '/tmp/id_rsa.pub')}}"
  loop: "{{ user_list }}"
  delegate_to: jcdevops20
