---
- name: create postfix instance
  hosts: devops02
  gather_facts: no
  vars:
    - role_postfix_instance_list:
      - {
        user: jcadmin,
        name: king,
        port: 961,
        group: AGE
        }
  roles:
    - { role: role postfix, state: create }
