---
- name: create postfix instances
  hosts: devops02
  gather_facts: no
  vars:
    project_user: jcadmin
    postfix_name: king
    postfix_port: 961
    postfix_group: AGE
  roles:
    - { role: role_postfix_instance, state: create}
