---
- name: deploy hadoop cluster users
  hosts: hadoop
  gather_facts: no
  become: true
  vars_files:
    - hadoop_password
  vars:
    hadoop_conf_dir:
      - /opt/cluster/hadoop-2.9.2
    hadoop_directory:
      - /data/
      - /data/datanode
      - /data/namenode
      - /data/journalnode/jchadcluster01
    hadoop_log_directory:
      - /var/log
      - /var/log/hadoop
    group_list:
      - {
        name: "hadoop",
        gid: "5000"
        }
      - {
        name: "hdfs",
        gid: "1008"
        }
      - {
        name: "yarn",
        gid: "1009"
        }
      - {
        name: "mapred",
        gid: "1010"
        }
    user_list:
      - {
        user: "hdfs",
        uid: "1008",
        group: "hdfs",
        groups: "hadoop",
        ssh_key: "yes"
        }
      - {
        user: "yarn",
        uid: "1009",
        group: "yarn",
        groups: "hadoop",
        ssh_key: yes
       }
      - {
        user: "mapred",
        uid: "1010",
        group: "mapred",
        groups: "hadoop",
        ssh_key: "yes"
       }

  tasks:
    - name: "create system group and users"
      include_role:
        name: role_manage_user
      vars:
        state: create

    - name: copy the hosts files on machine
      include_role:
        name: role_manage_system
        tasks_from: manage_hosts.yaml

    - name: "copy config file"
      include_role:
        name: role_hadoop
        tasks_from: deploy_file.yaml

    - name: "create directory"
      file:
        path: "{{ item }}"
        state: directory
        owner: hdfs
        group: hdfs
        mode: "0775"
        recurse: yes
      loop: "{{ hadoop_directory}}"

    - name: "create log directory"
      file:
        path: "{{ item }}"
        state: directory
        owner: hdfs
        group: hadoop
        mode: "0775"
        recurse: yes
      loop: "{{ hadoop_log_directory}}"

    - name: "apply the good rights"
      file:
        path: "{{hadoop_conf_dir}}"
        owner: "hdfs"
        state: directory
        recurse: yes
        force: yes

    - name: "configure secure zones"
      include_tasks: HDFS_encryption_at_Rest.yaml
      delegate_to: hadoop
