---
- name: "Create repo directory"
  file:
    path: "{{ role_sys_repo }}"
    state: directory

- name: enable service ntpd
  systemd:
    name: ntpd
    enabled: yes

- name: configure ntpd
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify: restart ntpd

# - name: configure hosts
#   template:
#     src: hosts.j2
#     dest: /etc/hosts

- name: "configure profile.d for {{ app_name }}"
  template:
    src: "{{ app_name }}.sh.j2"
    dest: "{{ role_sys_profile }}/{{ app_name }}.sh"

- name: "Execute profile.d for {{ app_name }}"
  command: . {{ role_sys_profile | quote }}/{{ app_name | quote }}
