---
- name: create directory
  file:
    path: "{{ item }}"
    state: directory
    group: "{{ sys_group }}"
    mode: "0774"
  with_items:
    - "{{ sys_bin }}"
    - "{{ sys_data }}"
    - "{{ sys_var }}"
    - "{{ sys_repo }}"
