---
- name: "create group {{ item.group }}"
  group:
    name: "{{ item.group }}"
    gid: "{{ item.gid }}"
    state: present

- name: "create user {{ item.user }}"
  user:
    name: "{{ item.user }}"
    groups: "{{ item.group }}"
    append: yes
    uid: "{{ item.uid }}"

- name: create directory
  file:
    path: "{{ item }}"
    state: directory
    group: "{{ item.group }}"
    mode: "0774"
  loop: "{{ role_system_dir }}"
