---
- name: install packages
  yum:
    name: " {{ sys_packages }}"
    update_cache: yes
  ignore_errors: true

- name: configure ntp
  template:
    src: "ntp.conf.j2"
    dest: "/etc/ntp.conf"
  notify: restart ntp

# - name: force synchronisation ntp
#   command: ntpdate fr.pool.ntp.org
