---
- name: install packages
  yum:
    name: " {{ packages }}"
    update_cache: yes
  ignore_errors: true

- name: configure ntp and hosts
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}"
  with_items:
    - ntp.conf
    - hosts
  notify: restart ntp

# - name: force synchronisation ntp
#   command: ntpdate fr.pool.ntp.org
