---
- name: install packages
  yum:
    name: "{{ sys_packages }}"
    update_cache: yes
  ignore_errors: true
  when: ansible_distribution == "Centos"

- name: install packages
  apt:
    name: "{{ sys_packages }}"
    update_cache: yes
    valid_cache: 3600
  ignore_errors: true
  when: ansible_distribution == "Ubuntu"

- name: configure ntp
  template:
    src: "ntp.conf.j2"
    dest: "/etc/ntp.conf"
  notify: restart ntp



# - name: force synchronisation ntp
#   command: ntpdate fr.pool.ntp.org
